"""Generate docs-internal/menu-map.md — which overlay section each feature lives in.

WHY THIS IS GENERATED, NOT WRITTEN. A hand-kept map drifts the moment someone adds a panel, and a
drifted map is worse than none: it was the absence of this that let Streamer mode ship under
"Companion plugins" (the horseACT/CarrotBlender section) because an insert was anchored on a
convenient regex match rather than a decided location. menu_model.rs is the single source of truth,
so read it.

    python native/tools/gen_menu_map.py            # print
    python native/tools/gen_menu_map.py --write    # write docs-internal/menu-map.md

COVERAGE CHECK: the script counts every `title: "..."` in the file and compares against how many
sections it actually attributed to a tab. A mismatch is reported loudly rather than silently
producing a short map - an incomplete map is the exact failure mode this is meant to prevent.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "native", "src", "menu_model.rs")
OUT = os.path.join(ROOT, "docs-internal", "menu-map.md")


def parse(src):
    """Line-based scan: attribute every `title:` to whichever vec is currently being built.

    The earlier regex version matched only two block shapes and silently found 19 of 33 sections.
    Walking lines and tracking the current vec cannot miss a block shape it has not seen before,
    which is what a map like this has to guarantee.
    """
    vec_to_tab = {
        m.group(2): m.group(1)
        for m in re.finditer(r'tabs\.push\(Tab \{ name: "([^"]+)".*?sections: (\w+)', src)
    }

    sections, cur_vec, cur_title, cur_ctrls = [], None, None, []

    def flush():
        if cur_title:
            sections.append((cur_vec, cur_title, list(cur_ctrls)))

    for line in src.splitlines():
        m = re.search(r"let mut (\w+) = vec!\[", line) or re.search(r"(\w+)\.push\(Section \{", line)
        if m:
            cur_vec = m.group(1)
        t = re.search(r'title:\s*"([^"]+)"', line)
        if t:
            flush()
            cur_title, cur_ctrls = t.group(1), []
        c = re.search(r"Ctrl::Custom\(Custom::(\w+)\)", line)
        if c and cur_title:
            cur_ctrls.append(f"`Custom::{c.group(1)}`")
        else:
            lab = re.search(r'Ctrl::(?:Toggle|Slider|Button).*?label: "([^"]+)"', line)
            if lab and cur_title:
                cur_ctrls.append(lab.group(1))
    flush()
    return vec_to_tab, sections


def main():
    src = open(SRC, encoding="utf-8").read()
    vec_to_tab, sections = parse(src)

    declared = len(re.findall(r'title:\s*"', src))
    if len(sections) != declared:
        print(
            f"!! COVERAGE: parsed {len(sections)} sections but the file declares {declared}.\n"
            f"   The map would be INCOMPLETE - fix the parser before writing.",
            file=sys.stderr,
        )
        return 1

    by_tab = {}
    for vec, title, ctrls in sections:
        by_tab.setdefault(vec_to_tab.get(vec, f"(unattached: {vec})"), []).append((title, ctrls))

    lines = [
        "# Overlay menu map",
        "",
        "GENERATED by `native/tools/gen_menu_map.py` from `native/src/menu_model.rs`. Do not edit by",
        "hand - regenerate. Every feature's home in the menu, so a new panel lands somewhere chosen",
        "rather than wherever an edit happened to be anchored.",
        "",
        f"{len(sections)} sections across {len(by_tab)} tabs.",
        "",
    ]
    for tab, rows in by_tab.items():
        lines += [f"## {tab}", "", "| Section | Controls |", "| --- | --- |"]
        for title, ctrls in rows:
            lines.append(f"| **{title}** | {', '.join(ctrls) if ctrls else '—'} |")
        lines.append("")

    doc = "\n".join(lines)
    if "--write" in sys.argv:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        open(OUT, "w", encoding="utf-8").write(doc)
        print(f"wrote {OUT} ({len(sections)} sections)")
    else:
        print(doc)
    return 0


if __name__ == "__main__":
    sys.exit(main())
